name: SpotBugs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  spotbugs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper/
          key: gradle-wrapper-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-wrapper-${{ runner.os }}-

      - name: Cache Gradle dependencies (cached files)
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches/
          key: gradle-caches-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            gradle-caches-${{ runner.os }}-

      - name: Install dependencies
        run: ./gradlew build

      - name: Run SpotBugs
        run: ./gradlew spotbugsMain spotbugsTest
