name: SpotBugs

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  spotbugs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17

      - name: Download build cache artifact
        uses: actions/download-artifact@v3
        with:
          name: build-cache
          path: ~/.gradle/caches/

      - name: Run SpotBugs
        run: ./gradlew spotbugsMain spotbugsTest
