name: Java CI with Gradle (Test)

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write  # Ensure we have write permissions to comment on PRs

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Grant execute permissions to gradlew
      - name: Grant execute permissions to gradlew
        run: chmod +x gradlew

      # Step 4: Run tests with Gradle
      - name: Run tests
        run: ./gradlew test

      # Step 5: List files for debugging
      - name: List files in the build directory
        run: |
          echo "Listing files in the build directory..."
          ls -R ./build

      # Step 6: Post test results to PR
      - name: Post test results on PR
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = './build/reports/tests/test/classes';  # Corrected path for test results

            if (!fs.existsSync(path)) {
              console.log("Test results directory not found!");
              return;
            }

            const testResults = [];
            const files = fs.readdirSync(path);

            if (files.length === 0) {
              console.log("No test result files found.");
              return;
            }

            files.forEach(file => {
              const filePath = `${path}/${file}`;
              if (filePath.endsWith('.html')) {
                testResults.push({
                  file: filePath,
                  result: 'HTML report available'
                });
              }
            });

            let comment = "### Test Results\n\n";
            testResults.forEach(result => {
              comment += `- ${result.file}:\n  - Report generated\n\n`;
            });

            comment += testResults.length > 0 ? "✅ **Test reports generated successfully**!" : "⚠️ **No test reports found**.";

            const prNumber = context.payload.pull_request.number;
            if (prNumber) {
              await github.rest.issues.createComment({
                issue_number: prNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            } else {
              console.log("No PR number found. Skipping comment creation.");
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
