name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Give permission to gradlew
    - name: Grant execute permissions to gradlew
      run: chmod +x gradlew  # Make gradlew executable

    # Step 4: Run Gradle build from the Pentago folder
    - name: Build with Gradle
      run: ./gradlew build

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    # Step 1: Checkout the code again for the dependency submission step
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up JDK 17 again
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Generate and submit the dependency graph
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4
