name: PMD

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  pmd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4  # Updated to v4
        with:
          java-version: 17

      - name: Cache Gradle wrapper
        uses: actions/cache@v3  # Updated to v3
        with:
          path: ~/.gradle/wrapper/
          key: gradle-wrapper-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-wrapper-${{ runner.os }}-

      - name: Cache Gradle dependencies
        uses: actions/cache@v3  # Updated to v3
        with:
          path: ~/.gradle/caches/
          key: gradle-caches-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            gradle-caches-${{ runner.os }}-

      - name: Install dependencies
        run: ./gradlew build

      - name: Run PMD
        run: ./gradlew pmdMain pmdTest
